.TH NUMBER-GAME 1 "2025-12-08" "Версия 1.1" "User Commands"
.SH NAME
number-game \- Simple number guessing game, supports Roman numerals.
.SH SYNOPSIS
number-game [OPTIONS]
.SH DESCRIPTION
.B number-game
guesses your number between 1 and 100 (optionally 3999) using binary search, can show numbers in Roman numerals.

Options:
.TP
.B -r
Use Roman numerals in input/output.
.TP
.B -h, --help
Show help.
